logging:
  level: INFO

nep:
  host: "0.0.0.0"
  port: 2525
  rate_limits:
    send: 100/hour
    list: 1000/hour
    fetch: 1000/hour

nept:
  host: "0.0.0.0"
  port: 2526
  rate_limits:
    send: 100/hour

neph:
  host: "0.0.0.0"
  port: 8080
  rate_limits:
    send: 100/hour
    list: 1000/hour

web:
  host: "0.0.0.0"
  port: 8000
  secret_key: "change_this_to_a_random_secret_key"

storage:
  type: "file"
  file:
    path: "./data"
    emails_dir: "emails"
    users_file: "users.json"
